# Windows DNS client needs to be set multiple times,
# 1) to ensure that forest  domain is reachable when installing child domain,
# 2) to ensure that other domains are reachable.
# AD server will use otherwise itself as DNS server and we would have to
# create glue records.

---
- hosts: ipa:ldap:client
  roles:
  - packages
  - common

- hosts: ad:ad-child
  roles:
  - win-common
  - win-dnsclient

- hosts: ad
  roles:
  - win-forest
  - win-dnsclient

- hosts: ipa
  roles:
  - ipa
  
- hosts: ad-child
  roles:
  - win-domain
  - win-dnsclient

- hosts: ipa:ldap:client
  roles:
  - dnsclient

- hosts: ldap
  roles:
  - ldap
  
- hosts: client
  roles:
  - sssd
