- name: Install packages
  become: True
  package:
    state: present
    name:
    - python2-winrm
    - python3-winrm
    - NetworkManager
    - dnsmasq
    - qemu-kvm
    - firewalld
  
- name: Create /etc/polkit-1/rules.d/00-org.libvirt.unix.manager.rules
  become: True
  template:
    src: polkit
    dest: /etc/polkit-1/rules.d/00-org.libvirt.unix.manager.rules
    owner: root
    group: root
    mode: 0644

- name: Allow services needed for NFS in firewall
  become: True
  shell: |
    firewall-cmd --list-services | grep {{ item | quote }}
    if [ $? -eq 0 ]; then
      echo "Service {{ item | quote }} is already enabled. Nothing to do."
      exit 255
    fi
     
    firewall-cmd --permanent --add-service={{ item | quote }}
  register: fw_result
  failed_when: "fw_result.rc != 255 and fw_result.rc != 0"
  changed_when: "fw_result.rc == 0"
  with_items:
  - nfs
  - mountd
  - rpc-bind

- name: Restart firewalld
  become: True
  service:
    name: firewalld.service
    enabled: yes
    state: reloaded
  when: fw_result.changed
