- name: Install packages
  become: True
  package:
    state: present
    name:
    - python2-winrm
    - python3-winrm
    - NetworkManager
    - dnsmasq
    - qemu-kvm
  
- name: Create /etc/polkit-1/rules.d/00-org.libvirt.unix.manager.rules
  become: True
  template:
    src: polkit
    dest: /etc/polkit-1/rules.d/00-org.libvirt.unix.manager.rules
    owner: root
    group: root
    mode: 0644
