- name: Remove hostname from /etc/hosts
  become: True
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.0\.1|::1)[ \t]+{{ ipa.hostname }}.*$'
    state: absent

- name: Install IPA server
  become: True
  shell: |
    /usr/sbin/ipa-server-install --unattended          \
      --realm={{ ipa.domain | upper | quote }}         \
      --domain={{ ipa.domain | quote }}                \
      --ds-password={{ ipa.password | quote }}         \
      --admin-password={{ ipa.password | quote }}      \
      --hostname={{ ipa.fqn | quote }}                 \
      --setup-dns                                      \
      --auto-forwarders                                \
      --auto-reverse                                   \
      --no-dnssec-validation                           \
      --no-host-dns
    RET=$?
    if [ $RET -ne 0 ]; then
      exit $RET
    fi
      
    /usr/sbin/ipa-adtrust-install --unattended         \
      --netbios-name={{ ipa.netbios | quote }}         \
      --admin-password={{ ipa.password | quote }}
    RET=$?
    if [ $RET -ne 0 ]; then
      exit $RET
    fi
  register: installed 
  args:
    creates: /etc/ipa/default.conf

- name: Remove IPA CA trust from previous installation
  become: True
  local_action:
    shell \
      FILE="{{ playbook_dir }}/../shared-enrollment/ipa/ca.crt"; \
      [ -f "$FILE" ] && /usr/bin/trust anchor --remove "$FILE" || exit 255
  register: result
  when: installed.changed
  failed_when: "result.rc != 255 and result.rc != 0"
  changed_when: "result.rc == 0"

- name: Copy certificate to shared folder
  become: True
  copy:
    force: True
    src: /etc/ipa/ca.crt
    dest: '/shared/enrollment/{{ inventory_hostname }}/'
    remote_src: yes
  register: cert_copy

- name: Trust IPA CA
  become: True
  local_action:
    shell /usr/bin/trust anchor "{{ playbook_dir }}/../shared-enrollment/ipa/ca.crt"
  when: cert_copy.changed

- name: 'Setup trust with {{ ad.domain }}'
  shell: |
    echo {{ ipa.password | quote }} | kinit admin
     
    ipa trust-show {{ ad.domain | quote }}
    if [ $? -eq 0 ]; then
      echo "Trust with {{ ad.domain | quote }} already exists. Nothing to do."
      exit 255
    fi
     
    echo vagrant | ipa trust-add {{ ad.domain | quote }} --admin Administrator --password
  register: result
  failed_when: "result.rc != 255 and result.rc != 0"
  changed_when: "result.rc == 0"
