- name: Remove hostname from /etc/hosts
  become: True
  lineinfile:
    path: /etc/hosts
    regexp: '^(127\.0\.0\.1|::1)[ \t]+{{ ipa.hostname }}.*$'
    state: absent

- name: Install IPA server
  become: True
  shell: |
    /usr/sbin/ipa-server-install --unattended          \
      --realm={{ ipa.domain | upper | quote }}         \
      --domain={{ ipa.domain | quote }}                \
      --ds-password={{ ipa.password | quote }}         \
      --admin-password={{ ipa.password | quote }}      \
      --hostname={{ ipa.fqn | quote }}                 \
      --setup-dns                                      \
      --auto-forwarders                                \
      --auto-reverse                                   \
      --no-dnssec-validation                           \
      --no-host-dns
    RET=$?
    if [ $RET -ne 0 ]; then
      exit $RET
    fi
      
    /usr/sbin/ipa-adtrust-install --unattended         \
      --netbios-name={{ ipa.netbios | quote }}         \
      --admin-password={{ ipa.password | quote }}
    RET=$?
    if [ $RET -ne 0 ]; then
      exit $RET
    fi
  register: ipa_installation
  args:
    creates: /etc/ipa/default.conf
