- name: 'Packages are the same as in Fedora 29'
  include_tasks: 'Fedora29.yml'

# - dbus-daemon was replaced with dbus-broker, but for now we need dbus-daemon
#   to run SSSD integration tests
# - Tool dbus-send is required for NetworkManager and it was extracted to
#   a new package.
- name: Install additional packages
  become: True
  dnf:
    state: present
    name:
    - dbus-daemon
    - dbus-tools
